In [1]:
import pandas as pd

In [2]:
path = "/content/students_one_hot_encoding_dataset.csv"

In [3]:
df = pd.read_csv(path)

In [4]:
df.head()

   Student_ID     Department     City    Education
0           1          Cloud   Sousse     Bachelor
1           2   Data Science     Sfax     Bachelor
2           3  Cybersecurity    Tunis     Bachelor
3           4            Web  Bizerte       Master
4           5   Data Science   Nabeul  High School

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
Hot = OneHotEncoder()

In [9]:
Hot.fit_transform(df[['City']]).toarray()

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [12]:
OneHot = pd.get_dummies(df, columns=['City'], dtype='int')

In [14]:
OneHot.head()

,Student_ID,Department,Education,City_Bizerte,City_Nabeul,City_Sfax,City_Sousse,City_Tunis
0,1,Cloud,Bachelor,0,0,0,1,0
1,2,Data Science,Bachelor,0,0,1,0,0
2,3,Cybersecurity,Bachelor,0,0,0,0,1
3,4,Web,Master,1,0,0,0,0
4,5,Data Science,High School,0,1,0,0,0